/*
 * Copyright (c) 2013-2015, ARM Limited, All Rights Reserved
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ***************************************************************
 *
 *  DO NOT CHANGE - this file has been autogenerated from:
 *
 *  https://github.com/ARMmbed/uvisor
 *    - core/mbed/source/uvisor-gcc-header.S
 *    - core/mbed/source/uvisor-gcc-input.S
 *
 ***************************************************************/
.globl uvisor_init
.globl uvisor_config
.globl uvisor_ctx
.type uvisor_init, %function
.weak __uvisor_mode
.section .uvisor.main, "x"
    .thumb
    .thumb_func
uvisor_init:
    .incbin "uvisor-MK64FN1M0XXX12.box"
uvisor_config:
    .long 0x2FE539A6
    .long 0
    .long __uvisor_mode
    .long __uvisor_bss_start
    .long __uvisor_bss_end
    .long __uvisor_bss_main_start
    .long __uvisor_bss_main_end
    .long __uvisor_bss_boxes_start
    .long __uvisor_bss_boxes_end
    .long __uvisor_main_start
    .long __uvisor_main_end
    .long __uvisor_secure_start
    .long __uvisor_secure_end
    .long __uvisor_cfgtbl_start
    .long __uvisor_cfgtbl_end
    .long __uvisor_cfgtbl_ptr_start
    .long __uvisor_cfgtbl_ptr_end
    .long __uvisor_box_context
__uvisor_mode:
    .long 0
.section .bss
__uvisor_box_context:
uvisor_ctx:
    .long 0
.section .keep.uvisor.bss.main, "awM", @nobits
    .space 0x2000
